title: Evolution for Everyone

theme: just-the-docs

url: https://Evolution-for-Everyone.github.io

nav_enabled: true

docs_dir: docs

# External navigation links
nav_external_links:
  - title: Evolution for Everyone on GitHub
    url: https://github.com/Evolution-for-Everyone/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
